import { createApp, h, type App } from 'vue';
import { VideoCutClient } from '../packages/client/index.mjs';
import { createProject, addAsset, ticks } from '../packages/core/project.mjs';
import { MediaEngine } from '../packages/media/browser';
import { sharedMediaClient } from '../packages/media/client';
import ClipVisual from '../src/editor/ClipVisual.vue';

const query=new URLSearchParams(location.search),fixtures=query.get('fixtures')||'/Users/jxinfa/WebstormProjects/videocut/.local/architecture-qa';
const reportURL=query.get('report')||'http://127.0.0.1:4333',client=new VideoCutClient(location.origin);
const status=document.querySelector('#status')!,results:any[]=[],logs:string[]=[];
let controller=new AbortController(),engine:MediaEngine,clipApp:App|undefined,session='';
const report:any={phase:'idle',started:'',userAgent:navigator.userAgent,longAudioFreshCache:query.has('cold'),results,logs};
async function publish(){status.textContent=JSON.stringify(report,null,2);await fetch(`${reportURL}/report`,{method:'POST',headers:{'Content-Type':'application/json','X-QA-Report':'media'},body:JSON.stringify(report)}).catch(()=>{});}
function check(condition:unknown,message:string):asserts condition{if(!condition)throw Error(message);}
function summary(values:number[]){const sorted=[...values].sort((a,b)=>a-b);return {n:values.length,min:sorted[0],median:sorted[Math.floor(sorted.length*.5)],p95:sorted[Math.min(sorted.length-1,Math.floor(sorted.length*.95))],max:sorted.at(-1)};}
async function one(name:string,work:()=>Promise<unknown>){report.phase=name;await publish();const begin=performance.now();const value=await work();results.push({name,milliseconds:performance.now()-begin,value});await publish();}
const delay=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
async function run(){
  const button=document.querySelector('#run') as HTMLButtonElement;button.disabled=true;controller=new AbortController();engine=new MediaEngine();report.started=new Date().toISOString();delete report.error;results.length=logs.length=0;
  const maxima={frameBytes:0,pcmBytes:0,waveformBytes:0,activeJobs:0,sources:0,jsHeapBytes:0};
  const sample=setInterval(()=>{const now=engine.stats();for(const key of ['frameBytes','pcmBytes','waveformBytes','activeJobs','sources'] as const)maxima[key]=Math.max(maxima[key],now[key]);maxima.jsHeapBytes=Math.max(maxima.jsHeapBytes,(performance as any).memory?.usedJSHeapSize||0);},20);
  try{
    await client.connect();
    report.phase='importing';await publish();
    const names=['timecode.mp4','vfr.mp4','stereo.wav','hour-pulses.flac'];
    const assets=await Promise.all(names.map(name=>client.importMedia(`${fixtures}/${name}`).then(v=>v.asset||v)));
    const project=createProject('Media acceptance');for(const asset of assets)addAsset(project,asset);const snapshot=await client.createSession(project);session=snapshot.id;
    const urls=assets.map((asset,index)=>client.mediaUrl(session,asset.id)+(asset.sourceIdentity&&!(index===3&&query.has('cold'))?'&source='+encodeURIComponent(asset.sourceIdentity):''));
    const reference=await (await fetch(`/@fs${fixtures}/media-pts.json`)).json();
    const requests=[0,.001,.033366,.033367,.1,.333333,.999,1.001,1.999,2,2.001,2.067,2.101,2.8,3.4,3.99];
    for(const index of [0,1])await one(index?'vfr_pts':'ntsc_2997_pts',async()=>{
      const expected=reference[names[index]] as number[],cold:number[]=[],warm:number[]=[],actual:any[]=[];
      for(const at of requests){controller.signal.throwIfAborted();const begin=performance.now();const frame=await engine.videoFrame(urls[index],at,{signal:controller.signal,width:320,height:180});cold.push(performance.now()-begin);const pts=expected.filter(t=>t<=at+1e-7).at(-1)!;check(Math.abs(frame.timestamp-pts)<2e-6,`Wrong ${names[index]} PTS at ${at}: ${frame.timestamp} != ${pts}`);actual.push({requested:at,expected:pts,actual:frame.timestamp});if(at===2.8)(document.querySelector('#frame') as HTMLCanvasElement).getContext('2d')!.drawImage(frame.frame,0,0,320,180);frame.close();}
      const before=engine.stats();for(const at of requests){const begin=performance.now();const frame=await engine.videoFrame(urls[index],at,{signal:controller.signal,width:320,height:180});warm.push(performance.now()-begin);frame.close();}const after=engine.stats();check(after.completed===before.completed,'Warm frames unexpectedly decoded');return{cold:summary(cold),warm:summary(warm),cacheHits:after.frameHits-before.frameHits,actual};
    });
    await one('cache_identity_across_sessions',async()=>{const other=await client.createSession(project);try{const before=engine.stats();const url=client.mediaUrl(other.id,assets[0].id)+'&source='+encodeURIComponent(assets[0].sourceIdentity);const frame=await engine.videoFrame(url,0,{width:320,height:180});frame.close();const after=engine.stats();check(after.completed===before.completed&&after.frameHits===before.frameHits+1,'Stable source did not reuse cached frame across sessions');return{cacheHits:after.frameHits-before.frameHits,newDecodeJobs:after.completed-before.completed};}finally{await client.closeSession(other.id);}});
    await one('sequential_vfr_cursor',async()=>{const reader=await engine.createVideoReader(urls[1],{signal:controller.signal,width:320,height:180});const times=Array.from({length:120},(_,i)=>i*1001/30000),latency:number[]=[];try{for(const at of times){const begin=performance.now();const frame=await reader.frameAt(at);latency.push(performance.now()-begin);const pts=reference['vfr.mp4'].filter((t:number)=>t<=at+1e-7).at(-1);check(Math.abs(frame.timestamp-pts)<2e-6,`Cursor PTS mismatch at ${at}`);frame.close();}for(const at of [1.2,.2,3.5]){const frame=await reader.frameAt(at);const pts=reference['vfr.mp4'].filter((t:number)=>t<=at+1e-7).at(-1);check(Math.abs(frame.timestamp-pts)<2e-6,'Reader backwards seek mismatch');frame.close();}return{samples:123,latency:summary(latency)};}finally{await reader.close();}});
    await one('bounded_parallel_decoders',async()=>{let maximum=0;const timer=setInterval(()=>{maximum=Math.max(maximum,engine.stats().activeJobs);},1);try{const frames=await Promise.all(Array.from({length:8},(_,i)=>engine.videoFrame(urls[0],.07+i*.37,{width:208,height:117})));frames.forEach(frame=>frame.close());check(maximum<=2&&maximum>0,'Decoder concurrency exceeded its budget');return{requests:8,observedActiveJobs:maximum,configuredConcurrency:2};}finally{clearInterval(timer);}});
    await one('shared_decode_and_cancellation',async()=>{const before=engine.stats();const frames=await Promise.all(Array.from({length:12},()=>engine.videoFrame(urls[0],1.234567,{width:200,height:120})));frames.forEach(frame=>frame.close());const after=engine.stats();check(after.completed-before.completed===1,'Identical requests were not deduplicated');const abort=new AbortController(),begin=performance.now();const pending=engine.thumbnails(urls[0],Array.from({length:256},(_,i)=>i*4/256),{signal:abort.signal});setTimeout(()=>abort.abort(),1);let cancelled=false;try{(await pending).forEach(frame=>frame.close());}catch(error){cancelled=error instanceof Error&&error.name==='AbortError';}check(cancelled,'Thumbnail request did not cancel');return{consumers:12,decodeJobs:after.completed-before.completed,cancelResponseMs:performance.now()-begin};});
    await one('stereo_numeric_waveform',async()=>{const wave=await engine.waveform(urls[2],0,4,1600,{signal:controller.signal});check(wave.channels.length===2,'Stereo channels collapsed');return{channels:wave.channels.map(ch=>({min:Math.min(...ch.min),max:Math.max(...ch.max)})),columns:1600};});
    await one('clip_visual_worker_dpr',async()=>{const item=project.timeline.tracks.flatMap(track=>track.items).find(item=>item.clip.assetId===assets[0].id)!;clipApp?.unmount();clipApp=createApp({render:()=>h(ClipVisual,{project,item,mediaUrl:(id:string)=>client.mediaUrl(session,id),zoom:180,viewportStartSeconds:0,viewportEndSeconds:4,height:54})});clipApp.mount('#clip');let drawn=false;for(let attempt=0;attempt<200;attempt++){controller.signal.throwIfAborted();await delay(50);const host=document.querySelector('#clip [data-visual-revision]') as HTMLElement|null;if(host?.dataset.visualError)throw Error(host.dataset.visualError);const canvas=host?.querySelector('canvas');if(canvas?.dataset.firstPts){drawn=true;break;}}check(drawn,'ClipVisual never published worker thumbnails');const canvas=document.querySelector('#clip canvas') as HTMLCanvasElement;return{dpr:devicePixelRatio,canvasWidth:canvas.width,cssWidth:canvas.getBoundingClientRect().width,firstPTS:canvas.dataset.firstPts,lastPTS:canvas.dataset.lastPts,worker:await sharedMediaClient.stats()};});
    await one('complete_one_hour_stereo_waveform',async()=>{const metadata=await engine.probe(urls[3]);check(Math.abs(metadata.duration-3600)<.01,'Long fixture is truncated');const before=engine.stats();const wave=await engine.waveform(urls[3],0,3600,7200,{signal:controller.signal,onProgress:seconds=>{if(seconds%300===0){report.longAudioAnalyzedSeconds=seconds;void publish();}}});check(wave.channels.length===2,'Long audio lost channels');const left=wave.channels[0],right=wave.channels[1];let leftPulses=0,rightPulses=0;for(let sec=0;sec<3600;sec+=10){const a=Math.floor((sec+.5)*2),b=Math.floor((sec+5.5)*2);check(left.max[a]>.89,`Missing left pulse at ${sec+.5}`);check(right.min[b]<-.79,`Missing right pulse at ${sec+5.5}`);leftPulses++;rightPulses++;}check(engine.stats().pcmBytes===before.pcmBytes,'Waveform retained full PCM');return{duration:metadata.duration,columns:7200,leftPulses,rightPulses,lastLeftPeak:left.max[7181],lastRightPeak:right.min[7191],cache:engine.stats()};});
    await one('one_hour_waveform_warm_cache',async()=>{const before=engine.stats();await engine.waveform(urls[3],0,3600,7200,{signal:controller.signal});return{before,after:engine.stats()};});
    report.phase='complete';report.completed=new Date().toISOString();
  }catch(error){report.phase=controller.signal.aborted?'cancelled':'failed';report.error=error instanceof Error?error.stack:String(error);}
  finally{clearInterval(sample);report.maximum=maxima;report.final=engine.stats();await publish();button.disabled=false;}
}
window.addEventListener('unhandledrejection',event=>{logs.push(String(event.reason?.stack||event.reason));void publish();});
document.querySelector('#run')!.addEventListener('click',()=>void run());document.querySelector('#stop')!.addEventListener('click',()=>controller.abort());
void publish();if(query.has('autorun'))void run();
